### PR TITLE
RHCLOUD-21717 minor UI issues on BG wizard review step

### PR DESCRIPTION
**Pull request by aferd**
Screen Shot 2022-11-16 at 3 29 10 PM

### CODE REVIEW

**Comment by aferd** [comment]
@jeromemarc

**Review by josejulio — APPROVED** [review]
lgtm

**Comment by aferd** [comment]
good to merge? I am unable to see anything on the why the build failed.

**Comment by josejulio** [comment]
> good to merge? I am unable to see anything on the why the build failed.

It's good to merge - build failure seems unrelated to this change.

Thanks!

**Pull request merged**
