### PR TITLE
feat: Event-Driven Ansible integration on preview

### PR DESCRIPTION
**Pull request by vkrizan**
Enables Event-Driven Ansible integrations on preview.

RHCLOUD-26202

### CODE REVIEW

**Comment by vkrizan** [comment]
@josejulio please review

**Review by josejulio — APPROVED** [review]

**Comment by josejulio** [comment]
This is going to stable-preview. I assume it is safe to move it to prod-preview, right?

**Comment by vkrizan** [comment]
@josejulio what's the difference between stable and prod?

**Comment by josejulio** [comment]
> @josejulio what's the difference between stable and prod?

sorry, lack of coffee :sweat: 
This should be already on stage-preview. It's save to move it to prod-preview? *

**Comment by vkrizan** [comment]
@josejulio yes, that's the idea to have it on preview available on production.

**Pull request merged**
