### PR TITLE
NOTIF-745 Adding banner to advertise Splunk integration in beta

### PR DESCRIPTION
**Pull request by josejulio**
Screenshot_2022-08-15_12-11-17

Peek 2022-08-15 12-10

### CODE REVIEW

**Comment by josejulio** [comment]
@jeromemarc and @mmenestr 
Could you take a look?

**Comment by mmenestr** [comment]
Could you add 24px of space between the bottom of the alert and the table? 
Also, should say "Set up splunk integration on **console.**redhat.com/beta" instead of on "**cloud.**redhat.com/beta", right?

**Comment by josejulio** [comment]
> Could you add 24px of space between the bottom of the alert and the table?
Just added the same space that I used on the notifications page. Could you verify that's OK? its a global_spacer_xl from patternfly. 

Should I change it on both pages to something else?

> Also, should say "Set up splunk integration on **console.**redhat.com/beta" instead of on "**cloud.**redhat.com/beta", right?

yes, thanks !

**Comment by josejulio** [comment]
Updated integrations screen:

Screenshot_2022-08-18_07-02-44

**Review by aferd — APPROVED** [review]
lgtm

**Pull request merged**
