### PR TITLE
Prod update

### PR DESCRIPTION
**Pull request by gwenneg**
- Remember to merge using the `Merge pull request/Create a merge commit` method and using `Prod update (Merge)` as commit title.
- Wait until branches `prod` and `prod-beta` from https://github.com/RedHatInsights/notifications-frontend-build repository are updated.
- Trigger the deployment in jenkins.

See prod deployment for more info.

### CODE REVIEW

**Comment by gwenneg** [comment]
@josejulio Do you know why there's a conflict? That's unusual.

**Comment by josejulio** [comment]
I think it's because last merge came from https://github.com/karelhala/notifications-frontend/tree/prod-release-04-24 from https://github.com/RedHatInsights/notifications-frontend/pull/400 instead of `master`.

**Comment by josejulio** [comment]
I guess we should first merge https://github.com/karelhala/notifications-frontend/tree/prod-release-04-24 into our master branch

**Comment by josejulio** [comment]
Fixed the conflicts - we had the same change in both branches, but the order in which they were applied was what triggered the conflict.

**Pull request merged**
