### PR TITLE
Prod update

### PR DESCRIPTION
**Pull request by gwenneg**
- Remember to merge using the `Merge pull request/Create a merge commit` method and using `Prod update (Merge)` as commit title.
- Wait until branches `prod` and `prod-beta` from https://github.com/RedHatInsights/notifications-frontend-build repository are updated.
- Trigger the deployment in jenkins.

See prod deployment for more info.

### CODE REVIEW

**Comment by josejulio** [comment]
@karelhala are these ready for prod?
- Enable overhaul navigation via feature flags (#444
- Notifications Landing Page (#443)

**Comment by karelhala** [comment]
@josejulio yup, they should be. Both of these features are hidden behind feature flags and should not be visible to folks unless specifically enabled in unleash.

**Comment by karelhala** [comment]
Checking the UI right now with disabled feature flag and looks like the navigation is not operating correctly. I'll see to it and create a hot fix, please hold this PR while we fix it.

**Comment by karelhala** [comment]
We need this PR in order to fix the broken navigation https://github.com/RedHatInsights/notifications-frontend/pull/450

**Comment by josejulio** [comment]
From previous discussion, it looks like we don't need this anymore

**Pull request closed without merging**
