### PR TITLE
NOTIF-475 UX Improvements Settings > Notifications

### PR DESCRIPTION
**Pull request by aferd**

### CODE REVIEW

**Comment by aferd** [comment]
https://user-images.githubusercontent.com/86322239/153918974-abe0b7eb-40e2-40fe-83ba-a05e012c8e91.mov

Fixes for Settings > Notifications

- Settings > Notifications titles should reflect the current selected bundle e.g. 'Notifications | Red Hat Enterprise Linux' instead of 'Notifications'.
- Title / Description in Settings > Notifications and Behavior Group description as helper (see attached mock).

**Comment by aferd** [comment]
this seems to be failing from the page header going from 'Notifications' to 'Notifications | Bundle'

**Comment by josejulio** [comment]
Yes, the smoke test seems to be failing because of the update: https://github.com/RedHatInsights/notifications-frontend/blob/master/test/SmokeTest.tsx#L244

**Review by josejulio — APPROVED** [review]
Perfect!

**Pull request merged**
