### PR TITLE
NOTIF-509 Adding slack integration

### PR DESCRIPTION
**Pull request by josejulio**
Peek 2022-03-09 13-49

Screenshot_2022-03-10_08-49-24

### CODE REVIEW

**Comment by josejulio** [comment]
@pilhuhn Is this OK? do you need more/less fields?

**Comment by pilhuhn** [comment]
Looks great. The SSL one could go away

**Comment by josejulio** [comment]
What SSL ?? :grin: 

Screenshot_2022-03-09_13-55-18

(just joking, i just removed it)

**Comment by theute** [comment]
@jeromemarc

**Comment by aferd** [comment]
tests failing due to a few lint errors

**Review by aferd — APPROVED** [review]

**Comment by pilhuhn** [comment]
The integrations list still shows the ssl, but not the channel
Bildschirmfoto 2022-03-10 um 15 51 47

**Comment by josejulio** [comment]
@pilhuhn updated to have a different expanded content for the slack integration

**Comment by josejulio** [comment]
@mmenestr adding a new integration type - this won't be on prod initially.

**Pull request merged**
