### PR TITLE
RHCLOUD-34527 - fix button url

### PR DESCRIPTION
**Pull request by aferd**
### Description

Incorrect redirection URL after Integration is created using wizard

[RHCLOUD-34527](https://issues.redhat.com/browse/RHCLOUD-34527)

---

#### After:

---

### Checklist ☑️
- [ ] PR only fixes one issue or story 
- [ ] Change reviewed for extraneous code 
- [ ] UI best practices adhered to 
- [ ] Commits squashed and meaningfully named 
- [ ] All PR checks pass locally (build, lint, test, E2E)

##
- [ ] _(Optional) QE: Needs QE attention (OUIA changed, perceived impact to tests, no test coverage)_
- [ ] _(Optional) QE: Has been mentioned_
- [ ] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [ ] _(Optional) UX: Has been mentioned_
##

### CODE REVIEW

**Review by karelhala — DISMISSED** [review]

**Review by InsaneZein — DISMISSED** [review]

**Review by fhlavac — COMMENTED** [review]
I would just keep also the `href` - the button will probably no longer support opening in a new tab via middle-click and it's maybe a bit cleaner approach.

**Comment by aferd** [comment]
> I would just keep also the `href` - the button will probably no longer support opening in a new tab via middle-click and it's maybe a bit cleaner approach.

so keep both? or just use the `href`?

**Comment by fhlavac** [comment]
I would probably keep both

**Review by fhlavac — APPROVED** [review]

**Pull request merged**
