### PR TITLE
NOTIF-260 Improve empty state on behavior group dropdown

### PR DESCRIPTION
**Pull request by josejulio**
Before:

Screenshot_2021-10-25_10-43-20
Screenshot_2021-10-25_10-43-42

After:

Screenshot_2021-10-25_10-43-11
Screenshot_2021-10-25_10-44-01

### CODE REVIEW

**Review by aferd — APPROVED** [review]

**Comment by mmenestr** [comment]
the "select behavior group" comes up when a user clicks the edit/pencil button right?

**Comment by josejulio** [comment]
> the "select behavior group" comes up when a user clicks the edit/pencil button right?

That's correct. It looks like this when not in edit mode (It wasn't changed):
Screenshot_2021-10-25_11-37-05

**Comment by mmenestr** [comment]
LGTM then! Just one comment, can you reduce the amount of space between the mute icon and the words "Mute"?

**Comment by josejulio** [comment]
top is 8px
bottom is 16px (current)

Screenshot_2021-10-25_11-50-18

**Comment by mmenestr** [comment]
Oh yes 8px is much better, thank you!!

**Comment by josejulio** [comment]
Screenshot_2021-10-25_11-58-41

**Pull request merged**
