### PR TITLE
feat: add new Ansible integration type

### PR DESCRIPTION
**Pull request by vkrizan**
The Ansible integration type is derived from the WebHook type. This will add support for Event-Driven Ansible.

RHCLOUD-25405

### CODE REVIEW

**Comment by vkrizan** [comment]
@josejulio can you please have a look at the CI error?
```
Firefox 63.0 (Linux x86_64) ERROR
  SyntaxError: expected expression, got '?'
  at dist/commons.js:2453:133
```
https://app.travis-ci.com/github/RedHatInsights/notifications-frontend/jobs/601334428
:pray:

**Comment by josejulio** [comment]
> @josejulio can you please have a look at the CI error?
> 
> ```
> Firefox 63.0 (Linux x86_64) ERROR
>   SyntaxError: expected expression, got '?'
>   at dist/commons.js:2453:133
> ```
> 
> https://app.travis-ci.com/github/RedHatInsights/notifications-frontend/jobs/601334428 pray

I recall that error from a library using syntax that made firefox unhappy. I'll fix that.

**Comment by josejulio** [comment]
I'm looking at that error in other PR as well - I'll fix on a follow up PR

**Pull request merged**
