### PR TITLE
Do not re-auth on chrome object ref change.

### PR DESCRIPTION
**Pull request by Hyperkid123**

### CODE REVIEW

**Review by ryelo — APPROVED** [review]

**Review by InsaneZein — APPROVED** [review]

**Review by josejulio — APPROVED** [review]
LGTM
silly me causing loops :sweat_smile:

**Comment by Hyperkid123** [comment]
@josejulio do you know whats up with the PR build?

**Comment by josejulio** [comment]
> @josejulio do you know whats up with the PR build?

No idea, looks like something changed somewhere. It says "No test report files were found"

> 14:43:38 ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?

**Comment by fhlavac** [comment]
I'll release the fix together with #476

**Pull request merged**
