### PR TITLE
Fix mobile styling of 'Create new behavior group' modal 

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-14023

Old
Screen Shot 2021-06-30 at 12 09 11 PM

New
Screen Shot 2021-06-30 at 12 06 48 PM

### CODE REVIEW

**Review by josejulio — CHANGES_REQUESTED** [review]
Thanks @epwinchell 

One issue with this approach is that we have the header (actions/recipient) each time for each row. I'm not sure how the mobile mock is, but the desktop one should have the header only once.

Screenshot_2021-06-30_11-17-51
Screenshot_2021-06-30_11-16-50

**Comment by epwinchell** [comment]
@josejulio The desktop layout hasn't changed:

Screen Shot 2021-06-30 at 12 21 51 PM

**Comment by epwinchell** [comment]
> One issue with this approach is that we have the header (actions/recipient) each time for each row

@josejulio Good catch. I could use some help with the logic to fix that when someone has time.

**Comment by josejulio** [comment]
> could use some help with the logic to fix that when someone has time.

I could help with that. Do you know how the UI should look in mobiles?

**Pull request closed without merging**
